### ISSUE TITLE
Mismatch of number of apps between CLI tool and flathub.org

### ISSUE THREAD

**Issue by ahayzen** [flathub/flathub#250]
When using the command `flatpak remote-ls flathub --app | wc -l` at this moment in time it reports 192 apps, where as https://beta.flathub.org/apps reports 183.

Here are the 'missing' 9 apps from the website

-  [x] com.github.bajoja.indicator-kdeconnect (**fails to build for other reasons**)
- [x] com.github.paolostivanin.OTPClient - https://github.com/paolostivanin/OTPClient/pull/49
- [x] org.quetoo.Quetoo
- [x] io.webtorrent.WebTorrent
- [x] org.filezillaproject.Filezilla
- [ ] net.pcsx2.PCSX2
- [x] com.github.quaternion 

~~-org.freedesktop.GlxInfo~~
~~-io.atom.electron.BaseApp~~

I do however think that `io.atom.electron.BaseApp` might be incorrectly shown in the CLI for --app ? Isn't this a BaseApp that other apps can run off and not one by itself ? Seems more like a runtime ?

**Comment by ahayzen** [comment]
`io.atom.electron.BaseApp` and `org.freedesktop.GlxInfo` shouldn't be shown in stores (eg the website) as they are apps that act like runtimes and don't have a .desktop file. These are false positives in the list and should be skipped :-)

**Comment by alexlarsson** [comment]
We now verify the id in the build, so we should not get new broken builds.

**Comment by TingPing** [comment]
So the wrong id ones are fixed. I didn't see anything obviously wrong with Quaternion and I think PCSX2 was never picked up because its i386 only and I think the apps are generated from x86_64 appstream data?

**Comment by AsciiWolf** [comment]
[com.obsproject.Studio](https://github.com/flathub/com.obsproject.Studio) is also missing.

**Comment by ahayzen** [comment]
@AsciiWolf it is there for me? https://beta.flathub.org/apps/details/com.obsproject.Studio

IIRC the old flathub.org apps page needs to be manually updated, whereas the new (beta) one is automatic and I can see it listed there.

**Comment by AsciiWolf** [comment]
@ahayzen Ah. That's weird, OBS Studio wasn't there where I checked it few days ago. And I am still not able to find OBS Studio in GNOME Software.

**Comment by ahayzen** [comment]
@AsciiWolf The pull request was only closed 19hours ago :-) https://github.com/flathub/flathub/pull/189 And maybe you need to run flatpak update, or update gnome-software's metadata, as I can find it in mine.

**Comment by AsciiWolf** [comment]
@ahayzen s/few days ago/yesterday/g. ;-) Yep, I ran flatpak update; I have just tried it again and it's still not there.

**Comment by TingPing** [comment]
```
flatpak update --appstream
pkill gnome-software
gnome-software --verbose
# See if found now otherwise look through logs for anything relevant
```

**Comment by ahayzen** [comment]
@TingPing for PCSX2, i386 apps can be installed on a x86_64 host right? (It seems to let me install it). So the app store should probably show this.

But this brings up another point, maybe the store needs the ability to filter by architecture ? As there are arm-only or non-arm apps etc.

Also, looks like $ flatpak search  is showing the same behavior as the store (not showing i386 apps).
```
$ flatpak --supported-arches 
x86_64
i386
$ flatpak search pcsx2
No matches found
$ flatpak search net.pcsx2.PCSX2
No matches found
$ flatpak install flathub net.pcsx2.PCSX2
Required runtime for net.pcsx2.PCSX2/i386/stable (org.freedesktop.Platform/i386/1.6) is not installed, searching...
Found in remote flathub, do you want to install it? [y/n]:
```

Maybe this needs separate issues raise though ? (one for the store to support filtering, one for flatpak search to show apps for all supported-arches)

**Comment by AsciiWolf** [comment]
@TingPing Yep, that's exactly what I tried two days ago and it didn't help. I have tried it again and the OBS Studio now shows in GNOME Software, so it probably just needed some time to update the AppStream metadata.

**Comment by ahayzen** [comment]
Watching the "Merge to main repo and update" step on buildbot for another project (https://flathub.org/builds/#/builders/2/builds/1112/steps/10/logs/stdio) I spotted the following errors.
```
(flatpak build-update-repo:8773): flatpak-WARNING **: Invalid id com.bajoja.com.github.bajoja.indicator-kdeconnect
(flatpak build-update-repo:8773): flatpak-WARNING **: Invalid id com.github.com.github.quaternion
```

Note that the others have been outputting
```
Extracting icons for component org.gnome.Builder.desktop
```

Does this give us a hint for `com.github.quaternion`? It seems to have a strange id ? `com.github.com.github.quaternion` ?

**Comment by TingPing** [comment]
@ahayzen I think that was a flatpak bug that was fixed, hopefully just triggering a new build solves it: https://flathub.org/builds/#/builders/1/builds/1999

**Comment by ahayzen** [comment]
@TingPing it worked thanks https://beta.flathub.org/apps/details/com.github.quaternion \o/ I'll tick it off the list.

**Comment by TingPing** [comment]
I suppose we can close this now unless you know of more. I think PCSX2 will be solved with https://github.com/jgarciao/linux-store-frontend/issues/39

**Comment by ahayzen** [comment]
Agreed, thanks for fixing the missing apps :-)
