### ISSUE TITLE
Quality guideline problems for 0 A.D. Empires Ascendant

### ISSUE THREAD

**Issue by StanleySweet** [flathub/flathub#6144]
### Flathub store page link

https://flathub.org/apps/details/com.play0ad.zeroad

### Questions or Feedback

I'm wondering how to handle the title correctly, since the full name is too long, and the short name contains a dot.
Also is it okay to have both dark and light branding colors to be the same ? I'm trying to address everything here https://github.com/flathub/com.play0ad.zeroad/pull/136/files

**Comment by razzeee** [comment]
> Also is it okay to have both dark and light branding colors to be the same ?

We usually fail you due to that, haven't seen, that anyone was able to pull that of.


FYI, we can't pass too long titles, as they get detected automatically.

I think the dot's could be fine here, but let's wait for @bertob

**Comment by StanleySweet** [comment]
> We usually fail you due to that, haven't seen, that anyone was able to pull that of.

Noted. Could you show me where it's used, it doesn't seem to make a difference on the website.

> FYI, we can't pass too long titles, as they get detected automatically.

0 A.D. is fine by me.

**Comment by razzeee** [comment]
> > We usually fail you due to that, haven't seen, that anyone was able to pull that of.
> 
> Noted. Could you show me where it's used, it doesn't seem to make a difference on the website.


For now it's mainly used for the banner you get, when we choose you for the homepage - see https://flathub.org/apps/com.play0ad.zeroad/bannerpreview for a preview

The light one is also used for the og image https://flathub.org/api/appOgImage/com.play0ad.zeroad instead of a boring white.

App stores might use it in more places and we might start using it in other places in the future.

**Comment by StanleySweet** [comment]
I see now thanks!

**Comment by StanleySweet** [comment]
So for the name how do I unblock the CI ?
https://github.com/flathub/com.play0ad.zeroad/pull/136

**Comment by razzeee** [comment]
That's a check of appstream and has nothing to do with quality checks. I don't think we can get around that, if anyone knows it's probably @bbhtt

**Comment by bbhtt** [comment]
> So for the name how do I unblock the CI ? [flathub/com.play0ad.zeroad#136](https://github.com/flathub/com.play0ad.zeroad/pull/136)

Should be fixed within the next 5-6 hours.

**Comment by StanleySweet** [comment]
Started another build. We'll see.

**Comment by StanleySweet** [comment]
Works fine thanks! I'm curious though I didn't have to update the submodule, so I don't know how it got repercuted.

Anyway that solves that issue :) 

Thanks for the fast replies folks.

I might need some help with https://github.com/flathub/com.play0ad.zeroad/issues/140 but that's another issue :)

**Comment by StanleySweet** [comment]
I use the branded wfg color. But maybe it wasn't the right call.

**Comment by bertob** [comment]
Just had a look at the latest version, unfortunately both the summary and brand colors still don't pass.

- Technical things like "open source" don't go in the summary
- Summaries should use sentence case
- Please avoid very light or very dark grays, the point of brand colors is to be colorful and distinct from neutral gray backgrounds :)

Summary suggestion: "Real-time strategy game"

Brand color suggestion:

```
<branding>
  <color type="primary" scheme_preference="light">#d6c49a</color>
  <color type="primary" scheme_preference="dark">#313131</color>
</branding>
```

![Image](https://github.com/user-attachments/assets/3a29ccbe-c5da-49a3-bdfd-d4a05200ed36)

**Comment by StanleySweet** [comment]
Okay I'll use your suggestion and make a new PR.
For the colors i copied Blender as I assumed they would have had figured it out, my bad.
I find the term "Brand color" misleading, as it has nothing to do with the brand (e.g. if you brand has bad colors you can't use them)

cc @TheShadowOfHassen

**Comment by razzeee** [comment]
> I find the term "Brand color" misleading, as it has nothing to do with the brand (e.g. if you brand has bad colors you can't use them)

For what it's worth, it's the branding of your app - so it's in a way your brand color, not sure it can be more specific to mean one but not the other. And spec in appstream uses `branding` https://www.freedesktop.org/software/appstream/docs/chap-Metadata.html#tag-branding unlikely, that will ever change.

**Comment by StanleySweet** [comment]
I see. Well too bad. :) In our case we use the wfg color for dark and light mode on the website.

Snap asked us to make a banner

https://dashboard.snapcraft.io/site_media/appmedia/2019/11/flatpackbanner_QKYFlgx.jpg

Anyway merged the fix, hopefully will be good this time around

**Comment by razzeee** [comment]
> EDIT: BTW it seems that github actions don't work any reason why? Could you enable them, or give me the rights to do so on my repo ?

Yeah, you're limited to a few. I don't think we enable them on demand @bbhtt sure knows

**Comment by bbhtt** [comment]
Enabled.

**Comment by StanleySweet** [comment]
Thank you. All is good now :)
